config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"
  get 'tags/:tag', to: 'recipes#index', as: :tag
  resources :users do
    get :recipes
    get :subscribe
    get :unsubscribe
    get :news
  end
  resources :recipes do
    resources :ingredients
    get :autocomplete_product_name, :on => :collection
    get :tags, :on => :collection
    member { post :vote }
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :product
  accepts_nested_attributes_for :product, :reject_if => :all_blank, :allow_destroy => true
  attr_accessor :product_name, :product_proteins, :product_carbs, :product_fat
  validates :weight, :product_id, :recipe_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ingredients
  has_many :recipes, :through => :ingredients
  validates :name, :proteins, :carbs, :fat, presence: { message: "не может быть пустым" }
  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true
  before_validation :recalc_calories, on: [:create, :update]

  def recalc_calories
    proteins = proteins ? proteins : 0
    carbs = carbs ? carbs : 0
    fat = fat ? fat : 0
    self.calories = proteins * 4 + carbs * 4 + fat * 9
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include ActionView::Helpers::UrlHelper
  include ActionController::UrlFor
  include Rails.application.routes.url_helpers

  has_many :ingredients
  has_many :products, :through => :ingredients
  belongs_to :user
  validates :name, presence: { message: "не может быть пустым" }
  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true
  attr_accessor :weight
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  before_validation :recalc_calories, :clear_ingredients_if_need, on: [:create, :update, :save]
  has_reputation :votes, source: :user
  slice :description, :as => :shorten, :slice => {:maximum => 300,:complete => /\n|\./}
  acts_as_taggable

  def recalc_calories
    if has_ingredients && ingredients && ingredients.length > 0
        self.calories = 0
        self.proteins = 0
        self.carbs = 0
        self.fat = 0
        total_weight = 0
        ingredients.each do |ingredient|
          if (ingredient.product)
            self.proteins = self.proteins + ingredient.product.proteins * ingredient.weight / 100
            self.carbs = self.carbs + ingredient.product.carbs * ingredient.weight / 100
            self.fat = self.fat + ingredient.product.fat * ingredient.weight / 100
            total_weight = total_weight + ingredient.weight;
          end
        end
        part = total_weight / 100
        self.proteins = (self.proteins / part).round
        self.carbs = (self.carbs / part).round
        self.fat = (self.fat / part).round
        self.calories = (calc_calories(proteins, carbs, fat) / part).round
    else
      self.calories = calc_calories(proteins, carbs, fat)
    end
  end

  private

  def clear_ingredients_if_need
    if has_ingredients == 0 || !has_ingredients
      self.ingredients.clear
    end
  end


  private

  def calc_calories(_proteins, _carbs, _fat)
    _proteins = _proteins ? _proteins : 0
    _carbs = _carbs ? _carbs : 0
    _fat = _fat ? _fat : 0
    _calories = _proteins * 4 + _carbs * 4 + _fat * 9
    _calories
  end

  private

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many(:users,
    :join_table => "subscribtions",
    :foreign_key => "owner_id",
    :association_foreign_key => "target_id")
  has_many :recipes
  has_many :evaluations, class_name: "RSEvaluation", as: :source
  has_reputation :votes, source: {reputation: :votes, of: :recipes}

  def voted_for?(recipe)
    evaluations.where(target_type: recipe.class, target_id: recipe.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def create
    @recipe = Recipe.find(params[:recipe_id])
    if (params[:ingredient][:product_id] && !params[:ingredient][:product_id].empty?)
      @ingredient = @recipe.ingredients.create(params[:ingredient].permit(:product_id, :weight))
      flash[:error] = "Не удалось добавить компонент. Проверьте введенные значения" if !@ingredient.valid?
      redirect_to edit_recipe_path(@recipe)
    else 
      product_params = params[:ingredient]
      @product = Product.new(name: product_params[:product_name], proteins: product_params[:product_proteins], carbs: product_params[:product_carbs],
                                fat: product_params[:product_fat])
      if (@product.save)
        @ingredient = @recipe.ingredients.create(product_id: @product.id, weight: product_params[:weight])
        redirect_to edit_recipe_path(@recipe)
      else
        flash.now[:error] = "Не удалось добавить продукт"
        render '/recipes/edit'
      end
    end
    @recipe.save
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy, :vote]

  autocomplete :product, :name, :extra_data => [:proteins, :carbs, :fat]

  def index
    if params[:tag]
    @recipes = Recipe.tagged_with(params[:tag]).paginate(:page => params[:page], per_page: 5).order("created_at DESC")
  else
    @recipes = Recipe.paginate(:page => params[:page], per_page: 5).order("created_at DESC")
  end
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to edit_recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to edit_recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def vote
    value = params[:type] == 'up' ? 1 : -1
    @recipe.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Спасибо за ваш голос"
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :proteins, :carbs, :fat, :description, :image, :has_ingredients, :tag_list)
  end

  def tags
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def recipes
    @recipes = Recipe.where(user_id: params[:user_id]).paginate(:page => params[:page], per_page: 5).order("created_at DESC")
  end

  def subscribe
    current_user.users << @user
    redirect_to user_recipes_path(@user)
  end

  def unsubscribe
    current_user.users.delete(@user)
    redirect_to user_recipes_path(@user)
  end

  def news
    @recipes = Recipe.where(user: current_user.users).paginate(:page => params[:page], per_page: 5).order("created_at DESC")
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ingredients/_form.html.haml
= simple_form_for([@recipe, @recipe.ingredients.build]) do |f|
  = f.input :product_id, as: :hidden, input_html: {id: "product_id"}
  = f.input :product_name, :url => autocomplete_product_name_recipes_path, :as => :autocomplete, :id_element =>"#product_id", :label => "Продукт", input_html: { class: 'form-control' }, update_elements: {proteins: "#product_proteins", carbs: "#product_carbs", fat: "#product_fat"}
  = f.input :product_proteins, input_html: {id: "product_proteins"}
  = f.input :product_carbs, input_html: {id: "product_carbs"}
  = f.input :product_fat, input_html: {id: "product_fat"}
  = f.input :weight, label: "Вес, г"
  %br/

  = f.button :submit, label: "Добавить"

app/views/ingredients/_ingredient.html.haml
%h2= ingredient.product.name
.row
  .col-md-1
    %p Белки:
    %h3= (ingredient.product.proteins * ingredient.weight / 100).round
  .col-md-1
    %p Углеводы:
    %h3= (ingredient.product.carbs * ingredient.weight / 100).round
  .col-md-1
    %p Жиры:
    %h3= (ingredient.product.fat * ingredient.weight / 100).round
  .col-md-1
    %p Вес, г:
    %h3= ingredient.weight.round
%hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FitFood
    = stylesheet_link_tag :application, :media => 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic"
    %body
      - if notice
        #notice_wrapper
          %p.notice= notice
      - elsif alert
        #alert_wrapper
          %p.alert= alert
      .brand 
        = link_to "Fit & Food", root_path
      .address-bar Вкусные и полезные рецепты
      %nav.navbar.navbar-default
        .container
          .navbar-header
            %button.navbar-toggle
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "Фитнес рецепты", root_path, class: "navbar-brand"
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li
                = link_to "Все рецепты", root_path
              - if user_signed_in?
                %li
                  = link_to "Мои", user_recipes_path(current_user)
                %li
                  = link_to "Лента", user_news_path(current_user)
                %li
                  = link_to "Добавить рецепт", new_recipe_path
              %li
                = link_to "Тэги", tags_recipes_path
            %p.navbar-text.pull-right
              - if user_signed_in?
                = link_to current_user.email, edit_user_registration_path, class: 'navbar-link'
                |
                = link_to 'Выход', destroy_user_session_path, method: :delete, class: 'navbar-link'
              - else
                = link_to 'Зарегистрироваться', new_user_registration_path, class: 'navbar-link'
                |
                = link_to 'Войти', new_user_session_path, class: 'navbar-link'
      .container
        = yield

app/views/recipes/_form.html.haml
%div{"data-no-turbolink" => true}
  = simple_form_for(@recipe, html: { class: "form-horizontal recipe_form" }) do |f|
    = f.input :name, label: "Название", input_html: { class: "form-control" }
    = f.input :description, label: "Как это приготовить?", input_html: { class: "ckeditor" }
    = f.input :tag_list, input_html: { value: @recipe.tag_list.join(",") }, label: "Тэги (через запятую)"
    = f.input :has_ingredients, as: :boolean, label: "Ввести ингредиенты вручную и рассчитать на их основе калорийность?"
    - if !@recipe.has_ingredients
      #recipe_parameters
        %p Введите состав на 100 г
        = f.input :proteins, label: "Белки", input_html: { class: "form-control" }
        = f.input :fat, label: "Жиры", input_html: { class: "form-control" }
        = f.input :carbs, label: "Углеводы", input_html: { class: "form-control" }

    = f.input :image, as: :file, inline_label: "Загрузить фото рецепта"
    %br/

    = f.button :submit, "Сохранить"

- if @recipe.has_ingredients
  #ingredients
    %p Ингредиенты:
    = render @recipe.ingredients
    %br/
    %h3 Добавить ингредиент
    = render 'ingredients/form'

app/views/recipes/_recipes.html.haml
#index_recipes
  - recipes.each do |recipe|
    .row
      .box
        .col-lg-12
          .recipe
            %hr
            .title
              = link_to recipe.name, recipe
            %p.text-center
              = "#{recipe.proteins} / #{recipe.fat} / #{recipe.carbs}"
              %br/
              = recipe.calories
            %hr
            - if recipe.image.exists?
              = image_tag recipe.image.url(:medium), class: "img-responsive img-border img-left"
            %hr.visible-xs
            %p= raw recipe.shorten
            - if recipe.description.length > 300
              = link_to "Читать полностью", recipe_path(recipe)
  .row
    .box
      .col-lg-12
        .pagination-box
          = will_paginate recipes, :previous_label => 'Предыдущая', :next_label => 'Следующая'

app/views/recipes/edit.html.haml
.row
  .box
    .col-lg-12
      %h1 Редактировать рецепт

      = render 'form'

      = link_to "Назад", recipe_path(@recipe), class: "btn btn-default"

app/views/recipes/index.html.haml
= render 'recipes', recipes: @recipes

app/views/recipes/new.html.haml
.row
  .box
    .col-lg-12
      %h1 Новый рецепт

      = render 'form'

      = link_to "Отменить", root_path

app/views/recipes/show.html.haml
.recipe
  .row
    .box
      .col-lg-12
        .recipe-block
          .title
            =@recipe.name
          - if @recipe.image.exists?
            = image_tag @recipe.image.url(:large)
          .row
            .col-md-12
              %p.text-center
                = "Белки: #{@recipe.proteins} / Жиры: #{@recipe.fat} / Углеводы: #{@recipe.carbs}"
                %br/
                = "Калории: #{@recipe.calories}"
          .recipe-description
            = raw @recipe.description
          .created-info.pull-right
            = link_to @recipe.user.email, user_recipes_path(@recipe.user)
            %p= @recipe.created_at.strftime("%H:%M %d-%m-%y")
          - if @recipe.has_ingredients
            #ingredients
              %p Ингредиенты:
              = render @recipe.ingredients
              %br/
        .reputation
          %p= "Рейтинг: #{@recipe.reputation_for(:votes).to_i}"
          = link_to "Нравится", vote_recipe_path(@recipe, type: "up"), method: "post"
          = link_to "Не нравится", vote_recipe_path(@recipe, type: "down"), method: "post"
        %br/
        .tags
          %p Тэги:
          %p= raw @recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
        %br/
        = link_to "Назад", root_path

        - if user_signed_in? && current_user.id == @recipe.user.id
          .pull-right
            = link_to "Редактировать", edit_recipe_path(@recipe)
            = link_to "Удалить", @recipe, method: :delete, data: { confirm: "Вы уверены?" }
        %hr/
        #disqus_thread
:javascript
  var disqus_identifier = "recipe_#{@recipe.id}";
  var disqus_url = 'http://example.com/recipes/#{@recipe.id}';
  var disqus_shortname = 'fitfood';
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://fitfood.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();

%noscript
  Please enable JavaScript to view the
  %a{:href=>"http://disqus.com/?ref_noscript=fitfood"} comments
  powered by Disqus.
%a.dsq-brlink{:href=>"http://disqus.com"}
  comments powered by 
  %span.logo-disqus Disqus

app/views/recipes/tags.html.haml
.row
  .box
    .col-lg-12
      .title
        Тэги
      #tag_cloud
        - tag_cloud Recipe.tag_counts, %w[s m l] do |tag, css_class|
          = link_to tag.name, tag_path(tag.name), class: css_class

app/views/users/news.html.haml
= render 'recipes/recipes', recipes: @recipes

app/views/users/recipes.html.haml
.row
  .box
    .col-md-4.col-md-offset-4.center
      %p= "#{@user.email} (#{@user.reputation_for(:votes).to_i})"
      - if current_user != @user
        - if current_user.users.include?(@user)
          = link_to "Отписаться", user_unsubscribe_path(@user)
        - else
          = link_to "Подписаться", user_subscribe_path(@user)
= render 'recipes/recipes', recipes: @recipes